[workspace]
resolver = "2"
members = [
    "co-jolt2",
    "co-jolt-coordinator",
    "jolt-core",
    "jolt-tracer",
    "jolt-common",
    "mpc-net",
    "mpc-core",
    "mpc-types",
]
exclude = [
    "jolt-sdk",
    "examples/fibonacci",
    "examples/sha2-chain",
]
default-members = [
    "co-jolt2",
    "co-jolt-coordinator",
    "mpc-net",
    "mpc-core",
    "mpc-types",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["timo <timofey@chainsafe.io>"]
description = "Co-Spartan implementation for Noir circuits"
license = "MIT"

[workspace.dependencies]
# ark-linear-sumcheck = {version = "0.5.0", features = ["parallel"]}
ark-linear-sumcheck = { git = "https://github.com/nulltea/sumcheck", features = [
    "parallel",
] }
ark-std = { version = "0.5.0", features = ["std"] }
ark-ff = { version = "0.5.0", features = ["parallel", "asm"] }
ark-bls12-381 = { version = "^0.5.0", default-features = false, features = [
    "curve",
] }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da", default-features = false, features = [
    "curve",
] }
ark-serialize = { version = "0.5.0", default-features = false }
ark-poly = { version = "0.5.0", features = ["parallel"] }
ark-ec = { version = "0.5.0", features = ["parallel"] }
ark-crypto-primitives = { version = "^0.5.0", default-features = false, features = [
    "sponge",
] }

tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
    "env-filter",
    "ansi",
    "registry",
    "std",
] }
tracing-forest = { version = "0.1.6", default-features = false, features = ["ansi", "smallvec"] }
tracing-chrome = "0.7"
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
base64 = "0.22.1"
divan = "0.1.21"
rand = "0.8.5"
subtle = "2.6.1"
bytemuck = "1.22.0"
hex-literal = "0.4.1"
hex = "0.4.3"
itertools = "0.12.0"
flate2 = "1.0"
bincode = "1.3"
postcard = { version = "1.1.1", features = ["use-std"] }
zstd = "0.13.3"
bytes = "1.10.1"
zeroize = "1.8.1"
num-bigint = "0.4.3"
eyre = "0.6.10"
color-eyre = "0.6.3"
bytesize = "2.0.1"
rand_chacha = "0.3.0"
toml = "0.9.5"
rustls = "0.23.15"
num-traits = { version = "0.2.18", default-features = false }
async-trait = "0.1.89"
thiserror = "2"
memmap2 = "0.9"

allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }



# Additional dependencies for co-spartan
clap = { version = "4.5", features = ["derive", "env"] }
mimalloc = { version = "*", default-features = false }
crossbeam = "0.8.3"
merlin = "3.0.0"
blake2 = "0.10"

mpc-types = { path = "./mpc-types" }
anyhow = "1.0.93"
argh = "0.1.12"

rayon = "1.10.0"
strum = { version = "0.26.3", default-features = false }
strum_macros = "0.26.4"

# Dependencies for local jolt-core
ark-grumpkin = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da", default-features = false }
ark-serialize-derive = { version = "0.5.0"}
jolt-optimizations = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
dory = { package = "dory-pcs", path = "./vendor/dory-pcs", features = ["backends", "cache", "disk-persistence"] }
# jolt-platform = { path = "/Users/timofey/repos/examples/jolt/jolt-platform", default-features = false }
# jolt-inlines-sha2 = { path = "/Users/timofey/repos/examples/jolt/jolt-inlines/sha2", default-features = false }
# jolt-inlines-keccak256 = { path = "/Users/timofey/repos/examples/jolt/jolt-inlines/keccak256", default-features = false }
sha3 = "0.10.8"
num-integer = "0.1.45"
num-derive = "0.4.2"
num = "0.4.3"
rand_core = { version = "0.6.4", default-features = false }
rand_distr = "0.4.3"
chrono = "0.4.42"
derive_more = { version = "2.0.1", features = ["from"] }
paste = "1.0.15"
lazy_static = "1.5.0"
once_cell = "1.19.0"
fixedbitset = "0.5.0"
inferno = { version = "0.12.3" }
memory-stats = { version = "1.0.0", features = ["always_use_statm"] }
serial_test = "3.2.0"
dirs = "5.0.1"
target-lexicon = "0.12.14"
reqwest = { version = "0.12.3", features = ["json", "blocking"] }
indicatif = "0.17.8"
tokio = { version = "1.38.0" }
common = { path = "./jolt-common", package = "jolt-common", default-features = false }
fnv = { version = "1.0.7", default-features = false }
object = { version = "0.36.7", features = ["build_core", "elf"], default-features = false }
addr2line = "0.25.1"

jolt-core = { path = "./jolt-core" }
tracer = { path = "./jolt-tracer", package = "jolt-tracer", default-features = false }
jolt-common = { path = "./jolt-common", package = "jolt-common" }
# jolt = { path = "/Users/timofey/repos/examples/jolt/jolt-sdk", package = "jolt-sdk" }

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da", default-features = false }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
# ark-bls12-381 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }


[profile.guest]
inherits = "release"
debug = false

[profile.release]
debug = true

[profile.test]
opt-level = 3
lto = "off"

# [patch."https://github.com/nulltea/jolt.git"]
# jolt-core = { path = "../jolt/jolt-core" }
# jolt-common = { path = "../jolt/common", package = "common" }
# jolt-tracer = { path = "../jolt/tracer", package = "tracer" }
