[package]
name = "co-jolt-coordinator"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Coordinator-side MPC proving for co-jolt2"
license.workspace = true

[dependencies]
mpc-core = { path = "../mpc-core" }

jolt-core.workspace = true
jolt-common.workspace = true
tracer = { workspace = true }

ark-bn254.workspace = true
ark-std.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true
ark-poly-commit.workspace = true
eyre.workspace = true
tracing.workspace = true
rayon = "1.10.0"
itertools.workspace = true
dory = { git = "https://github.com/markosg04/dory", branch = "dev/twist-shout" }
rand.workspace = true
num-traits.workspace = true
strum = "0.26.3"
snarks-core = { path = "../snarks-core" }

[features]
rv64 = ["jolt-core/rv64", "jolt-common/rv64", "tracer/rv64"]

[dev-dependencies]
co-jolt2 = { path = "../co-jolt2", features = ["test-utils"] }
rcgen = "0.13"
