my_id = 0
is_coordinator = true
worker = 0
bind_addr = "0.0.0.0:20000"
key_path = "data/key_coordinator.der"

[[parties]]
id = 0
worker = 0
dns_name = "localhost:10000"
cert_path = "data/cert0_0.der"

[[parties]]
id = 1
worker = 0
dns_name = "localhost:10001"
cert_path = "data/cert0_1.der"

[[parties]]
id = 2
worker = 0
dns_name = "localhost:10002"
cert_path = "data/cert0_2.der"

[coordinator]
dns_name = "localhost:20000"
cert_path = "data/cert_coordinator.der"
