[package]
name = "sha2-chain"
version = "0.1.0"
edition = "2021"

[workspace]
exclude = ["guest"]

[dependencies]
jolt-sdk = { path = "../../jolt-sdk", features = ["host"] }
guest = { package = "sha2-chain-guest", path = "./guest" }
co-jolt2 = { path = "../../co-jolt2" }
jolt-core = { path = "../../jolt-core", features = ["host"] }
tracer = { path = "../../jolt-tracer", package = "jolt-tracer", default-features = false }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da", default-features = false, features = ["curve"] }
ark-serialize = { version = "0.5.0", default-features = false }
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi", "registry", "std"] }

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", rev = "2b22f4959e89bd0656f4f261c3a854c29b87a7da" }
allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }

[profile.release]
debug = true
