[package]
name = "zkemail"
version = "0.1.0"
edition = "2021"

[workspace]
exclude = ["guest"]

[features]
default = []
rv64 = [
    "guest/rv64",
    "provia-jolt-sdk/rv64",
    "provia-worker/rv64",
    "jolt-core/rv64",
    "tracer/rv64",
    "jolt-inlines-sha2/rv64",
    "jolt-inlines-rsa/rv64",
    "zkemail-core/rv64",
]

[dependencies]
provia-jolt-sdk = { path = "../../provia-jolt-sdk", features = ["host"] }
guest = { package = "zkemail-guest", path = "./guest" }
provia-worker = { path = "../../provia-worker" }
jolt-core = { path = "../../jolt-core", features = ["host"] }
tracer = { path = "../../jolt-tracer", package = "jolt-tracer", default-features = false }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout", default-features = false, features = ["curve"] }
ark-serialize = { version = "0.5.0", default-features = false }
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-forest = { version = "0.1.6", default-features = false, features = ["ansi", "smallvec"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "ansi", "registry", "std"] }

# Host-side email parsing & DKIM
cfdkim = { git = "https://github.com/risc0-labs/dkim" }
mailparse = "0.14"
trust-dns-resolver = "0.23"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
base64 = "0.21"
jolt-inlines-sha2 = { path = "../../jolt-inlines/sha2", features = ["host"] }
jolt-inlines-rsa = { path = "../../jolt-inlines/rsa", features = ["host"] }
num-bigint = "0.4"
slog = "2.7"

# Shared types
zkemail-core = { path = "./core" }

[dev-dependencies]
provia-worker = { path = "../../provia-worker", features = ["test-utils"] }
provia-coordinator = { path = "../../provia-coordinator" }
provia-jolt-sdk = { path = "../../provia-jolt-sdk", features = ["host"] }
jolt-inlines-bigint = { path = "../../jolt-inlines/bigint", features = ["host"] }
postcard = { version = "1.0.8", default-features = false, features = ["use-std"] }
rsa = { version = "=0.9.6" }
sha2 = { version = "0.10", features = ["oid"] }
rand = "0.8"
rand_chacha = "0.3"

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
ark-bn254 = { git = "https://github.com/a16z/arkworks-algebra", branch = "dev/twist-shout" }
allocative = { git = "https://github.com/facebookexperimental/allocative", rev = "85b773d85d526d068ce94724ff7a7b81203fc95e" }

[profile.release]
debug = true
