[package]
name = "mpc-core"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint.workspace = true
ark-std.workspace = true
ark-ff.workspace = true
ark-bn254.workspace = true
ark-serialize.workspace = true
ark-poly.workspace = true
ark-ec.workspace = true
ark-linear-sumcheck.workspace = true
rand.workspace = true
itertools.workspace = true
eyre.workspace = true
color-eyre = { workspace = true, optional = true }
rayon = { version = "1.10.0", optional = true }
rand_chacha.workspace = true
tracing.workspace = true
num-traits = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
bytesize = { workspace = true }
parking_lot = "0.12.0"
mpc-net = { path = "../mpc-net" }
jolt-core.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[features]
default = ["std", "parallel"]
std = ["ark-ff/std", "ark-poly/std", "ark-std/std", "ark-serialize/std"]
parallel = [
    "std",
    "ark-ff/parallel",
    "ark-ec/parallel",
    "ark-poly/parallel",
    "ark-std/parallel",
    "rayon",
]
test-utils = ["std", "color-eyre"]
reuse-preproc = []
ring-msm = []
